name: waisteeny
favicon: null
layout_spectrum: 0.298620059620589
typography_spectrum: 0.18625869904644787
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.1476559224538505
  lightness: 0.07334881252609193
  saturation: 0.24796437565237284
  rhythmicContrast: 0.6546341872308403
purpose: []
